// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3-3B4jxW9jSC_oI0ouqyFvJq0gGrtGV8',
    appId: '1:194882469213:web:41a0837001599e79a63cb4',
    messagingSenderId: '194882469213',
    projectId: 'chat-app-test-865c1',
    authDomain: 'chat-app-test-865c1.firebaseapp.com',
    storageBucket: 'chat-app-test-865c1.appspot.com',
    measurementId: 'G-QJ1L40LP8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6i8OU0wSGmQvAOjE9NKpxxDPHHqsUyNY',
    appId: '1:194882469213:android:bc7762fdd0bde18fa63cb4',
    messagingSenderId: '194882469213',
    projectId: 'chat-app-test-865c1',
    storageBucket: 'chat-app-test-865c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKu3A9PLeAVDtdVYxYIHwrrkHU3jD35Fo',
    appId: '1:194882469213:ios:3c3d7c7738a39fdaa63cb4',
    messagingSenderId: '194882469213',
    projectId: 'chat-app-test-865c1',
    storageBucket: 'chat-app-test-865c1.appspot.com',
    iosBundleId: 'com.example.evcharge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKu3A9PLeAVDtdVYxYIHwrrkHU3jD35Fo',
    appId: '1:194882469213:ios:3c3d7c7738a39fdaa63cb4',
    messagingSenderId: '194882469213',
    projectId: 'chat-app-test-865c1',
    storageBucket: 'chat-app-test-865c1.appspot.com',
    iosBundleId: 'com.example.evcharge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3-3B4jxW9jSC_oI0ouqyFvJq0gGrtGV8',
    appId: '1:194882469213:web:1a0e655cff75ef74a63cb4',
    messagingSenderId: '194882469213',
    projectId: 'chat-app-test-865c1',
    authDomain: 'chat-app-test-865c1.firebaseapp.com',
    storageBucket: 'chat-app-test-865c1.appspot.com',
    measurementId: 'G-1D3X3XCNCM',
  );

}